# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barnaby "Southclaw" Keene
email: SouthclawJK@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programmer (C/++/Pawn/Python/JS), Video Editor (Premiere Pro), Motion Graphics
  (After Effects, Maya), Graphic Design (Illustrator), Photography (Nikon D5500,
  Lightroom), Musician (Guitar, Synths, Sequencers)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://southclaw.net" # the base hostname & protocol for your site
twitter_username: SouthclawJK
github_username:  Southclaw

# Build settings
markdown: kramdown

# Post stuff
excerpt_separator: <!--more-->

# Google services
google_analytics: UA-78828365-1
